CREATE TYPE "PixPaymentType" AS ENUM ('SUBSCRIPTION', 'CREDIT_PURCHASE');
ALTER TABLE "PixPayment" ADD COLUMN "type" "PixPaymentType" NOT NULL DEFAULT 'SUBSCRIPTION';
ALTER TABLE "PixPayment" ADD COLUMN "creditQty" INTEGER;
